#!/usr/bin/env bash

regex="([^/]+)-(.+)-cache-config.yaml"

for file in ~/.edgemicro/*; do
    if [[ $file =~ $regex ]]; then
        org=${BASH_REMATCH[1]}
        env=${BASH_REMATCH[2]}
        key=$(grep '\bkey:' $file | cut -d':' -f2)
        secret=$(grep '\bsecret:' $file | cut -d':' -f2)
        break
    fi
done

if [[ -z "$org" ]]; then
    echo ERROR: {org}-{env}-cache-config.yaml not found in ~/.edgemicro
    exit 1
fi

NODE_TLS_REJECT_UNAUTHORIZED=0 ./cli/edgemicro start -o $org -e $env -k $key -s $secret
